### ISSUE TITLE
TODO: TEXTURES

### ISSUE THREAD

**Issue by WForst-Breeze** [RS-WFB/Enhanced-Stonebricks#2]
### Blocks
- [ ] *传送门框架 [Translation: pending]*

### Items
- [ ] *精华 (RELIC) [Translation: pending]*
- [ ] *精华 (VITALITY) [Translation: pending]*
- [ ] *精华 (DESTRUCTION) [Translation: pending]*
- [ ] *精华 (SOUL) [Translation: pending]*
- [ ] *精华 (END) [Translation: pending]*
- [ ] *精华 (DESERT) [Translation: pending]*
- [ ] *精华 (OCEAN) [Translation: pending]*
- [ ] *精华 (NETHER) [Translation: pending]*

### Tools & Armor
- [ ] Pickaxe (RELIC)
- [x] Axe (VITALITY)
- [x] Sword (DESTRUCTION)
- [x] Bow (SOUL)
- [x] ~Helmet (END)~ *Need Further Discussion*
- [x] ~Chestplate (DESERT)~ *Need Further Discussion*
- [ ] ~Leggings (OCEAN)~ *Need Further Discussion*
- [ ] ~Boots (NETHER)~ *Need Further Discussion*

**Comment by RS-gty** [comment]
- [ ] 1. 自然守护者护甲「藤蔓缠身·森语者」
- [ ] *2. 熔火行者护甲「烈焰锻铸·余烬行者」
- [ ] 3. 亡灵低语护甲「骸骨共鸣·守夜人」
- [x] *4. 风暴追逐者护甲「雷鸣疾走·闪袭者」
- [ ] 5. 时蚀龙鳞护甲「时蚀龙鳞·永恒回响」（时间操控主题）
- [ ] *6. 虚空漫游者护甲「虚空漫游者·裂隙行者」（维度穿梭主题）
- [ ] 7. 幽匿共生护甲「幽匿共生·噬魂者」（腐化生物科技主题）

- [ ] 空白护甲包
